<?xml version="1.0" encoding="utf-8" ?> 
<StaticModuleInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                         xmlns="http://schemas.datacontract.org/2004/07/PlantiT.Base.Infra.Global.Implementation.DataStructure.Serializable">
  <Description>LmsModule</Description>
  <Version>0.0.0</Version>
  <Services>
    <Service>
      <TechName>LmsService</TechName>
      <Version>0.0.0.0</Version>
      <StartUpOrder>0</StartUpOrder>
      <CommandPromptArguments></CommandPromptArguments>
      <FileExtension>.exe</FileExtension>
    </Service>
  </Services>
  <Dependencies />
</StaticModuleInformation>